## NumPy: Numerical Data Handling

NumPy: Numerical Data Handling

The array object in NumPy is called **ndarray**

**Shape:**

The shape of an array is like its size.
It tells you **how many rows and how many columns **(or more layers if bigger)

*   List item
*   List item

the array has.

👉 Example:
If you have numbers arranged like a small table with 2 rows and 3 columns, its shape is (2, 3).

**Shape**

Tells you the structure of the array.

Represented as a tuple, where each number is the length of that dimension.

*   List item
*   List item



Example:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.shape)  # (2, 3) → 2 rows, 3 columns

shape = layout (rows × cols × …)

size = total elements

An array class in Numpy is called as **ndarray**.



In [ ]:
## Creating Numpy array.
import numpy as np

num = [1,2,3,4,5]
arr = np.array(num)
print("One D Array", arr)

zeros_arr = np.zeros([4,4])
print("Zeros array","\n", zeros_arr)

ones_arr = np.ones((3,3))
print("2D array of ones", "\n", ones_arr)

range_arr = np.arange(1,13)
print("Generating numpy array in range", "\n", range_arr) # Note: arange() always create only 1D array.

arange_2D = range_arr.reshape(3,4)
print(f"2D array with arange: \n {arange_2D}")

const_arr = np.full((4,3, 3), 5)
print("Constant Array", "\n", const_arr)

line_space = np.linspace(0,2, 5) # divides the number between range 0 to 2 in 5 equal sizes
print("Array wioth specified distance in between", "\n", line_space)

print("check  number of dimentions")
print("Dimention of arr: ", arr.ndim)
print("Dimention of zeros arr", zeros_arr.ndim)
print("Dimention of ones arr", ones_arr.ndim)
print("Dimention of range arr", range_arr.ndim)
print("Dimention of const arr", const_arr.ndim)








One D Array [1 2 3 4 5]
Zeros array 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2D array of ones 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Generating numpy array in range 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
2D array with arange: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Constant Array 
 [[[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]]]
Array wioth specified distance in between 
 [0.  0.5 1.  1.5 2. ]
check  number of dimentions
Dimention of arr:  1
Dimention of zeros arr 2
Dimention of ones arr 2
Dimention of range arr 1
Dimention of const arr 3


In [ ]:
### Create Python Numpy Arrays Using Random Number Generation.

random_array = np.random.rand(2,3)
print("Random Array: ", "\n",random_array)

randn_arr = np.random.randn(2,3)
print("Random normal: ", "\n", randn_arr)

int_rand = np.random.randint(1,10, size=(2,3))
print("Random integer: ", "\n", int_rand)



Random Array:  
 [[0.37803979 0.92054961 0.89974476]
 [0.33363143 0.59658206 0.49925805]]
Random normal:  
 [[ 1.1304129  -0.94799627 -0.00535884]
 [ 1.54060795 -0.06565281 -0.78194736]]
Random integer:  
 [[6 6 4]
 [3 5 5]]


Numpy Array Indexing

In [ ]:
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(array)

print("Accessing 1st value: ", array[0,1])
print("Accessing 2nd row's 3rd value: ", array[1,2])


multi_d_arr = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(multi_d_arr[1, 2, 0])



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Accessing 1st value:  2
Accessing 2nd row's 3rd value:  7
16


3. Slicing Arrays

In [ ]:
array = np.array([1,2,3,4,5,6,7,8])
print(array[1:3])
print(array[2:])
print(array[::5])

print("******************************")

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print("----------------------")
print("2nd row 3rd element: ","\n", matrix[0:2]) # 2nd would not be considred
print("1st row 3rd element: ","\n", matrix[0:2, 1:3])

[2 3]
[3 4 5 6 7 8]
[1 6]
******************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------
2nd row 3rd element:  
 [[1 2 3]
 [4 5 6]]
1st row 3rd element:  
 [[2 3]
 [5 6]]


Boolean Indexing

In [ ]:
print(array[array > 2])
arr = np.array([10, 15, 20, 25, 30])

print(arr[(arr > 10) & (arr < 30)])

[3 4 5 6 7 8]
[15 20 25]


Modifying Array Elements

In [ ]:
arr1 = np.array([10, 15, 20, 25, 30])
arr1[1:3] = 99
print(arr1)

arr1[4] = 12
print(arr1)

[10 99 99 25 30]
[10 99 99 25 12]


Reshaping array:

**syntax:**

np.reshape(arr, shape)

np.reshape(array, (2, -1))

The first number (2) means: "I want 2 rows."

The -1 tells NumPy:
👉 "You figure out how many columns I need, based on the total number of elements."

In [ ]:
reshape_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("Original array",reshape_arr)

reshape1 = np.reshape(reshape_arr , (4,4))
print("Reshaped array","\n", reshape1)

reshape2 = np.reshape(reshape_arr, (2,2,4))
print("Reshaped array2","\n", reshape2)

reshape3 = np.reshape(reshape_arr, (4, -1))
print("Reshaped array3","\n", reshape3)

reshape4 = np.reshape(reshape_arr, (2, -1))
print("Reshaped array4","\n", reshape4)


resha = np.reshape(reshape_arr, (8, -1))
print("unknown shaped array4","\n", resha)

Original array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Reshaped array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Reshaped array2 
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Reshaped array3 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Reshaped array4 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
unknown shaped array4 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


Numpy numpy.resize(), we can resize the size of an array.

In [ ]:
# importing the python module numpy
import numpy as np

# Making a random array
gfg = np.array([1, 2, 3, 4, 5, 6])

# Required values 12, existing values 6
gfg.resize(3, 4)

print(gfg)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use **reshape(-1) **to do this.

Example
Convert the array into a 1D array:

import numpy as np




In [ ]:
flatt_arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = flatt_arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

multi_dim_arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array using ravel()
flattened_arr_ravel = multi_dim_arr.ravel()

print("Original multi-dimensional array:", multi_dim_arr)
print("Flattened array using ravel():", flattened_arr_ravel)

Original multi-dimensional array: [[1 2 3]
 [4 5 6]]
Flattened array using ravel(): [1 2 3 4 5 6]


Broadcasting in Numpy:
- Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them.

- It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions.


In [ ]:
#Broadcasting a Scalar to a 1D Array

arr_1 = np.array([1, 2, 3])
res = arr_1 + 1
print(res)


#Broadcasting a 1D Array to a 2D Array
array1 = np.array([10,20,30,40,50])
array2 = np.array([[5,10,15,20,30], [21,22,23,24,25]])
add = array1 + array2
print("Broadcasting a 1D Array to a 2D Array Addition")
print(add)

multi = array1 * array2
print("Broadcasting a 1D Array to a 2D Array Multiplication")
print(multi)


[2 3 4]
Broadcasting a 1D Array to a 2D Array Addition
[[15 30 45 60 80]
 [31 42 53 64 75]]
Broadcasting a 1D Array to a 2D Array Multiplication
[[  50  200  450  800 1500]
 [ 210  440  690  960 1250]]


Broadcasting in Conditional Operations

In [ ]:


ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


### **Pandas:**

In [ ]:
import pandas as pd

# Creating Pandas Series
seris = pd.Series([1,2,3,4,5])
print(seris)


# Giving custome name to series index

cust_series = pd.Series([1,2,3,4,5,6,7], index= ['a', 'b', 'c', 'd', 'e', 'f', 'g'])
print('Cutome Series index names: ',"\n ", cust_series)


dict_series = pd.Series({"day1" : 420, "day2" : 380, "day3" : 390})
print(dict_series)


0    1
1    2
2    3
3    4
4    5
dtype: int64
Cutome Series index names:  
  a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64
day1    420
day2    380
day3    390
dtype: int64


## **Pandas** **DataFrame**




In [ ]:
# Creating dataframe

dataframe = pd.DataFrame({
    'name':['Varsha', 'Dhwani', 'Yash', 'Naitik', "Aarya"],
    "Age" : [24, 24,26,17,19]
})

print(dataframe)

     name  Age
0  Varsha   24
1  Dhwani   24
2    Yash   26
3  Naitik   17
4   Aarya   19


In [ ]:
# Reading csv file

df = pd.read_csv("data.csv")
print(df)

# To print all entire data
print("To print the entire data", df.to_string())

#viewing the last rows of the DataFrame.
print(df.tail())

# To get more info about the dataset
print(df.info())

print(df.describe())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]
To print the entire data      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10      

# **Cleaning Empty Cells**

# remove rows

Note: default, the dropna() method returns a new DataFrame, and will not change the original.

If you want to change the original DataFrame, use the inplace = True argument:

In [ ]:
new_df = df.dropna()
print(new_df)

df.dropna(inplace = True)

# Replace Empty value
df.fillna(130, inplace = True)

# Add a sample 'Date' column (assuming daily data for demonstration)
df['Date'] = pd.to_datetime(pd.date_range(start='2020/12/01', periods=len(df), freq='D'))

df.head()
print(df.duplicated())


     Duration  Pulse  Maxpulse  Calories       Date
0          60    110       130     409.1 2020-12-01
1          60    117       145     479.0 2020-12-02
2          60    103       135     340.0 2020-12-03
3          45    109       175     282.4 2020-12-04
4          45    117       148     406.0 2020-12-05
..        ...    ...       ...       ...        ...
164        60    105       140     290.8 2021-05-09
165        60    110       145     300.0 2021-05-10
166        60    115       145     310.2 2021-05-11
167        75    120       150     320.4 2021-05-12
168        75    125       150     330.4 2021-05-13

[164 rows x 5 columns]
0      False
1      False
2      False
3      False
4      False
       ...  
164    False
165    False
166    False
167    False
168    False
Length: 164, dtype: bool


## **Data Preprocessing in Python**

In [2]:
import matplotlib as plt

x = [1, 2, 3, 4]
y = [10, 20, 25, 30]
plt.subplot(1, 2, 1)  # (rows, cols, chart_number)
plt.plot(x, y)

plt.subplot(1, 2, 2)
plt.bar(x, y)

plt.show()

AttributeError: module 'matplotlib' has no attribute 'subplot'

In [3]:
import torch

# 1D tensor
vector = torch.tensor([1, 2, 3])

# 2D tensor (matrix)
matrix = torch.tensor([[1, 2], [3, 4]])

# 3D tensor
tensor3d = torch.randn(10, 50, 30)

print(vector.shape)    # torch.Size([3])
print(matrix.shape)    # torch.Size([2, 2])
print(tensor3d.shape)  # torch.Size([10, 50, 30])

torch.Size([3])
torch.Size([2, 2])
torch.Size([10, 50, 30])
